### ISSUE TITLE
Support Bounded Generics in Methods

### ISSUE THREAD

**Issue by spraguep** [UnquietCode/Flapi#3]
Trying to add a method that uses generics:

``` java
addMethod("withApplicationSettings(Class<? extends com.a.b.c.ApplicationSettings> settingsClass)")
```

Causes this exception:

``` java
Caused by: unquietcode.tools.flapi.MethodParser$ParseException: Expected to find character in {)} but was '?' (method signature is [ 'withApplicationSettings(Class<? extends com.paypal.creditpd.rappstack.server.flapi.application.RSApplicationSettings> settings)' ]).
    at unquietcode.tools.flapi.MethodParser.throwUnexpectedCharException(MethodParser.java:273)
    at unquietcode.tools.flapi.MethodParser.match(MethodParser.java:214)
    at unquietcode.tools.flapi.MethodParser.<init>(MethodParser.java:120)
    at unquietcode.tools.flapi.MethodParser.<init>(MethodParser.java:42)
    at unquietcode.tools.flapi.DescriptorPreValidator._checkForInvalidMethodSignatures(DescriptorPreValidator.java:119)
```

**Comment by UnquietCode** [comment]
#214 will add support for wildcards, and this issue can remain open for a future enhancement to implement bounded generics, which is much more difficult.
